name: bert_cls
embedding:
  type: bert
  name: bert-base-uncased
  dimension: 768
  use_local: true
  path: /home/pretrained/bert-base-uncased
max_seq_len: 512
dataset:
  name: imdb
  path: ./data/aclImdb
train:
  accelerator: gpu
  accelerator_devices: 1
  epochs: 100
  num_workers: 8
  train_batch_size: 16
  dev_batch_size: 16
  test_batch_size: 16
  precision: 16
  accumulate_grad: 8
optimizer:
  lr: 1e-5  #  warning: a large learning rate will break the parameter of BERT
  weight_decay: 0.0005
model:
  dropout: 0.1
  num_classes: 2
log_path: ./logs
log_every_n_steps: 10
sqlite_path: ./database/ml.db
onnx_path: ./exported
