name: text_cnn
embedding:
  type: random
  dimension: 300
max_seq_len: 128
dataset:
  name: imdb
  path: ./data/aclImdb
train:
  accelerator: gpu
  accelerator_devices: 1
  epochs: 20
  num_workers: 8
  train_batch_size: 128
  dev_batch_size: 128
  test_batch_size: 128
  optimizer:
    lr: 1e-3
model:
  dropout: 0.5
  num_filters: 256
  filter_sizes: [2, 3, 4]
  num_classes: 2
log_path: ./logs
