name: text_rnn
embedding:
  type: random
  dimension: 300
max_seq_len: 128
dataset:
  name: imdb
  path: ./data/aclImdb
train:
  accelerator: gpu
  accelerator_devices: 1
  epochs: 10
  num_workers: 8
  train_batch_size: 128
  dev_batch_size: 128
  test_batch_size: 128
optimizer:
  lr: 1e-3
model:
  hidden_size: 128
  num_layers: 2
  bidirectional: true
  dropout: 0.5
  num_classes: 2
log_path: ./logs
log_every_n_steps: 10
sqlite_path: ./database/ml.db
