name: "text_cnn_bert_tensorrt"
platform: "tensorrt_plan"
max_batch_size: 128
dynamic_batching { }
input [
  {
    name: "input"
    data_type: TYPE_INT32
    dims: [ 128 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
