name: "text_cnn_bert_pipeline"
platform: "ensemble"
max_batch_size: 128
input [
  {
    name: "pipeline_input"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "pipeline_output"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "text_preprocess"
      model_version: 1
      input_map: {
        key: "preprocess_input"
        value: "pipeline_input"
      }
      output_map: {
        key: "preprocess_output"
        value: "input_ids"
      }
    },
    {
      model_name: "text_cnn_bert_tensorrt"
      model_version: 1
      input_map: {
        key: "input"
        value: "input_ids"
      }
      output_map: {
        key: "output"
        value: "pipeline_output"
      }
    }
  ]
}
